# Inventory file for Ansible with details of managed hosts

# Section for Ubuntu instances
[ubuntu]
54.221.48.142 ansible_user=ubuntu ansible_ssh_private_key_file=/key-pair/key-pair-jc.pem ansible_python_interpreter=/usr/bin/python3
# IP address of the Ubuntu instance. SSH user is 'ubuntu'. The private key for SSH authentication is located at /key-pair/key-pair-jc.pem.
# The Python 3 interpreter path is /usr/bin/python3.

# Section for RHEL instances
[rhel]
54.165.84.31 ansible_user=ec2-user ansible_ssh_private_key_file=/key-pair/key-pair-jc.pem ansible_python_interpreter=/usr/bin/python3
# IP address of the RHEL instance. SSH user is 'ec2-user'. The private key for SSH authentication is located at /key-pair/key-pair-jc.pem.
# The Python 3 interpreter path is /usr/bin/python3.

# Section for Amazon Linux instances
[amazon_linux]
52.91.93.58 ansible_user=ec2-user ansible_ssh_private_key_file=/key-pair/key-pair-jc.pem ansible_python_interpreter=/usr/bin/python3
# IP address of the Amazon Linux instance. SSH user is 'ec2-user'. The private key for SSH authentication is located at /key-pair/key-pair-jc.pem. 
# The Python 3 interpreter path is /usr/bin/python3.