apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
      - name: admin-portal
        image: admin-portal:nginX
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: mysql-service  # Service name of the MySQL database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: admin-portal  # Match the labels used by your user microservice deployment
  ports:
    - protocol: TCP
      port: 3000   # Port used by user microservice
      targetPort: 80  # Port on the user microservice pod to forward traffic to
      # nodePort: 30100