---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal-service
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: admin-portal  # Match the labels used by your admin portal deployment
  ports:
    - protocol: TCP
      port: 3000   # Port used by admin portal
      targetPort: 80  # Port on the admin portal pod to forward traffic to

---
apiVersion: v1
kind: Service
metadata:
  name: landing-portal-service
spec:
  type: ClusterIP
  selector: #********************** !!! Change line below for green deployemnt !!! **************************
    app: landing-portal-green # Match the labels used by your user microservice deployment
  ports:
    - protocol: TCP
      port: 3001   # Port used by user microservice
      targetPort: 80  # Port on the user microservice pod to forward traffic to
#      nodePort: 31001  # Specify the nodePort value here

---
apiVersion: v1
kind: Service
metadata:
  name: member-dashboard-service
spec:
  type: ClusterIP
  selector:
    app: member-dashboard  # Match the labels used by your user microservice deployment
  ports:
    - protocol: TCP
      port: 3007   # Port used by user microservice
      targetPort: 80  # Port on the user microservice pod to forward traffic to
#      nodePort: 31007  # Specify the nodePort value here