apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==  # base64-encoded
  MYSQL_USER: YWRtaW4=  # base64-encoded username
  MYSQL_PASSWORD: bmltZGEzMjE=  # base64-encoded password
  MYSQL_DATABASE: YWxpbmVfZmluYW5jaWFsX2Ri