# Define the API version for the Secret resource
apiVersion: v1
# Specify the kind of Kubernetes resource, which is a Secret in this case
kind: Secret
# Metadata section for the Secret
metadata:
  # The name of the Secret
  name: mysql-secrets
# Type of the Secret, which is Opaque (generic)
type: Opaque
# Data section for storing sensitive information
data:
  # Base64-encoded MySQL root password
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==  # base64-encoded password
  # Base64-encoded MySQL username
  MYSQL_USER: cm9vdA==  # base64-encoded username
  # Base64-encoded MySQL user password
  MYSQL_PASSWORD: cm9vdF9wYXNzd29yZA==  # base64-encoded password
  # Base64-encoded MySQL database name
  MYSQL_DATABASE: YWxpbmVfZmluYW5jaWFsX2Ri  # base64-encoded database name
