import string
import random
from faker import Faker
import datetime
from .get_bank_branches_info import get_bank_information
from .get_account_info import *
from .create_transactions import create_transaction

class colors:
    RESET = '\033[0m'
    RED = '\033[91m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    MAGENTA = '\033[95m'
    CYAN = '\033[96m'
    WHITE = '\033[97m'

# Initialize faker instance and random choices
fake = Faker()
options = ['member', 'admin']


def generate_password():
    # Define the character sets
    lowercase_letters = string.ascii_lowercase
    uppercase_letters = string.ascii_uppercase
    digits = string.digits
    symbols = '@$!%*?&'  # Specify special symbols

    # Ensure at least one of each character type
    password = [random.choice(lowercase_letters),
                random.choice(uppercase_letters),
                random.choice(digits),
                random.choice(symbols)]

    # Generate the remaining characters
    password.extend(random.choices(lowercase_letters + uppercase_letters + digits + symbols, k=random.randint(4, 16)))
    random.shuffle(password)  # Shuffle the characters for randomness
    return "".join(password)

def generate_fake_phone_number():
    area_code = random.randint(100, 999)
    exchange_code = random.randint(100, 999)
    subscriber_number = random.randint(1000, 9999)
    phone_number = f"{area_code}-{exchange_code}-{subscriber_number}"
    return phone_number

def generate_ssn_like_string(format_string="XXX-XX-XXXX"):
  """Generates a random string in the specified format (e.g., XXX-XX-XXXX)."""
  digits = [str(random.randint(0, 9)) for _ in range(len(format_string.replace("-", "")))]

  # Create a formatted string using list comprehension and string joining
  output = "-".join(["".join(digits[:3]), "".join(digits[3:5]), "".join(digits[5:])])

  return output

def generate_date_of_birth():
    # Calculate the date 18 years ago
    eighteen_years_ago = datetime.date.today() - datetime.timedelta(days=365 * 18)
    onehundred_twenty_years_ago = datetime.date.today() - datetime.timedelta(days=365 * 120)

    date_of_birth = fake.date_of_birth()
    while not (onehundred_twenty_years_ago <= date_of_birth <= eighteen_years_ago):
        date_of_birth = fake.date_of_birth()

    date_of_birth_str = date_of_birth.strftime("%Y-%m-%d")
    return date_of_birth_str

def generate_data(generate_type):
    if generate_type == 'user':
        # At the moment only creates Admin users
        role = input(colors.YELLOW + "Type in 'admin' or 'member' to initiate creation details: " + colors.RESET)
        username = fake.user_name()
        while len(username) < 6:
            username += random.choice(string.ascii_letters)
        # Initialize password generated by password function
        password = generate_password()

        # Need to wait for the application data generation functions
        if role == 'member':
            membership_id = input(colors.CYAN + "Please provided membership id: " + colors.RESET)
            last_four_of_ssn = input(colors.CYAN + "Please provided the last four digits of the social: " + colors.RESET)

            return {
                "username": username,
                "password": password,
                "role": role,
                "membershipId": membership_id,
                "lastFourOfSSN": last_four_of_ssn

            }
        elif role == "admin":
            first_name = fake.first_name()
            last_name = fake.last_name()
            email = fake.email()
            phone = generate_fake_phone_number()

            # Create dictionary with key values pairs
            return {
                "username": username,
                "password": password,
                "role": role,
                "first_name": first_name,
                "last_name": last_name,
                "email": email,
                "phone": phone
            }
        else:
            return 'Error'
    elif generate_type == 'application':
        # Generate application-specific data
        application_amount = random.randint(10000, 100000)  # Adjust range as needed
        deposit_account_number = ''.join(random.choices(string.digits, k=10))  # Generate a 10-digit number for account
        application_type = random.choice(["CHECKING", "SAVINGS", "CHECKING_AND_SAVINGS"])
        middle_name = random.choice(["John","Smith", None])
        date_of_birth = generate_date_of_birth()
        gender = random.choice(["MALE", "FEMALE"])
        social_security = generate_ssn_like_string()
        drivers_license = ''.join(random.choices(string.digits, k=8))
        income = random.randint(100000, 8000000)
        address = fake.street_address()
        city = fake.city()
        state = fake.state()
        zipcode = fake.zipcode()
        no_new_applicants = "false"
        card_offer_id = 1
        applicant_ids = []
        first_name = fake.first_name()
        last_name = fake.last_name()
        email = fake.email()
        phone = generate_fake_phone_number()


        # Create dictionary with key values pairs
        return {
            "applicationType": application_type,
            "noNewApplicants": no_new_applicants,
            "applicantIds": applicant_ids,
            "applicants": [{
                "firstName": first_name,
                "middleName": middle_name,
                "lastName": last_name,
                "dateOfBirth": date_of_birth,
                "gender": gender,
                "email": email,
                "phone": phone,
                "socialSecurity": social_security,
                "driversLicense": drivers_license,
                "income": income,
                "address": address,
                "city": city,
                "state": state,
                "zipcode": zipcode,
                "mailingAddress": address,
                "mailingCity": city,
                "mailingState": state,
                "mailingZipcode": zipcode
            }],
            "applicationAmount": application_amount,
            "cardOfferId": card_offer_id,
            "depositAccountNumber": deposit_account_number
        }
    elif generate_type == 'bank':
            # Generate application-specific data
            routing_number = ''.join(random.choices(string.digits, k=9))
            address = fake.street_address()
            city = fake.city()
            state = fake.state()
            zipcode = fake.zipcode()

            # Create dictionary with key values pairs
            return {
                "routingNumber": routing_number,
                "address": address,
                "city": city,
                "state": state,
                "zipcode": zipcode
            }
    elif generate_type == 'branch':
            # Generate application-specific data
            name = random.choice(["Main Branch", "North Branch", "East Branch", "South Branch", "West Branch"])
            address = fake.street_address()
            city = fake.city()
            state = fake.state()
            zipcode = fake.zipcode()
            phone = generate_fake_phone_number()

            # Output usable bank info
            get_bank_information()
            bank_id = int(input(colors.YELLOW + "Enter an id from the list above. " + colors.RESET))

            # Create dictionary with key values pairs
            return {
                "name": name,
                "address": address,
                "city": city,
                "state": state,
                "zipcode": zipcode,
                "phone": phone,
                "bankID": bank_id
            }
    elif generate_type == 'transaction':
        transaction_type = random.choice(["DEPOSIT", "WITHDRAWAL", "TRANSFER_OUT", "PURCHASE", "PAYMENT", "REFUND"])
        method = random.choice(["ACH", "ATM", "APP"])
        amount = random.randint(200, 10000)
        merchant_code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
        merchant_name = fake.company()
        description = fake.text(max_nb_chars=255)

        if transaction_type == "TRANSFER_OUT":
            print(f"The selected transaction was a transfer type: {transaction_type}.")
            from_account_id = random.choices(get_account_id())
            to_account_id = random.choices(get_account_id())
            to_account_number = get_account_balance_or_account_by_id(to_account_id, "account")

            while from_account_id == to_account_id:
                to_account_id = random.choices(get_account_id())

            from_account_number = get_account_balance_or_account_by_id(from_account_id, "account")
            if get_account_balance_or_account_by_id(from_account_id, "balance") <= amount:
                create_transaction("DEPOSIT", "ACH", amount+1000, merchant_code='00000001',
                                    merchant_name='Deposit to the Rescue LLC', description=None,
                                      account_number=from_account_number, hold=False)

            print(colors.GREEN + "from account:", from_account_number, "to account:",
                   to_account_number, f"a {transaction_type} was made." + colors.RESET)
            memo = fake.text(max_nb_chars=50)

            return {
                "transfer": "True",
                "fromAccountNumber": from_account_number,
                "toAccountNumber": to_account_number,
                "amount": amount,
                "memo": memo,
            }
        else:
            print(f"The selected transaction type was {transaction_type}")
            account_id = random.choices(get_account_id())
            account_number = get_account_balance_or_account_by_id(account_id, "account")
            hold = "false"

            if transaction_type not in ["DEPOSIT", "REFUND"]:
                if get_account_balance_or_account_by_id(account_id, "balance") <= amount:
                    create_transaction("DEPOSIT", "ACH", amount+1000, merchant_code='00000001',
                                        merchant_name='Deposit to the Rescue LLC', description=None,
                                        account_number=account_number, hold=False)
                    print(colors.GREEN + "Inserted money into account because there was insufficient funds! I gotcha ;) " + colors.RESET)

            return {
                "transfer": "False",
                "type": transaction_type,
                "method": method,
                "amount": amount,
                "merchantCode": merchant_code,
                "merchantName": merchant_name,
                "description": description,
                "accountNumber": account_number,
                "hold": hold
            }
    else:
        return "Whoops. Working on this current feature."